# -*- coding: utf-8 -*-
"""Zoltan_Gaspar_Unit3Sprint2Module1Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p6a814MMNNio7jwXElyndMIFxkP_rKZ-
"""

import pandas as pd

df = pd.read_csv('buddymove_holidayiq.csv')
df.shape

df.isnull().sum()

import sqlite3
conn = sqlite3.connect('buddymove_holidayiq.sqlite3')
c = conn.cursor()

c.execute('CREATE TABLE BUDDYMOVE (User Id, Sports, Religious, Nature, Theatre, Shopping, Picnic)')
conn.commit()
df.to_sql('BUDDYMOVE', conn, if_exists='replace', index = False)

c.execute('SELECT * FROM BUDDYMOVE').fetchall()

c.close() 
conn.commit()